#!/usr/bin/env python3
"""
Manim Studio — First time setup
Gets you a free Groq API key and saves it to engine/.env
"""
import os, webbrowser
from pathlib import Path

ENV_FILE = Path(__file__).parent / ".env"

def main():
    print("\n🎬 Manim Studio — First Time Setup\n")
    
    existing = {}
    if ENV_FILE.exists():
        for line in ENV_FILE.read_text().splitlines():
            if "=" in line and not line.startswith("#"):
                k, v = line.split("=", 1)
                existing[k.strip()] = v.strip()
    
    print("You need a free Groq API key.")
    print("Groq is free, fast, and requires no credit card.\n")
    
    groq_key = existing.get("GROQ_API_KEY", "")
    
    if groq_key:
        print(f"✓ Groq key already set: {groq_key[:8]}...")
    else:
        open_browser = input("Open console.groq.com to get your free key? (y/n): ")
        if open_browser.lower() == "y":
            webbrowser.open("https://console.groq.com/keys")
            print("\nSign up → API Keys → Create key → copy it\n")
        
        groq_key = input("Paste your Groq API key here: ").strip()
    
    # Optional keys
    print("\nOptional: Gemini key for fallback (press Enter to skip)")
    gemini_key = existing.get("GEMINI_API_KEY", "")
    if not gemini_key:
        gemini_key = input("Gemini API key (optional): ").strip()
    
    # Write .env
    env_content = f"""# Manim Studio Engine Config
# Generated by setup.py

# PRIMARY — Free, no billing needed
# Get yours at: https://console.groq.com/keys
GROQ_API_KEY={groq_key}

# FALLBACK — Optional
GEMINI_API_KEY={gemini_key}
OPENAI_API_KEY={existing.get("OPENAI_API_KEY", "")}

# Rendering
MANIM_OUTPUT_DIR=./outputs
PREVIEW_RESOLUTION=480p
FINAL_RESOLUTION=1080p
"""
    ENV_FILE.write_text(env_content)
    print(f"\n✅ Saved to engine/.env")
    
    # Test the key
    if groq_key:
        print("\nTesting Groq connection...")
        try:
            from groq import Groq
            client = Groq(api_key=groq_key)
            client.chat.completions.create(
                model="llama-3.1-8b-instant",
                messages=[{"role": "user", "content": "Say OK"}],
                max_tokens=5,
            )
            print("✅ Groq key works! You're ready to go.\n")
            print("Start the app: cd web && npm run dev\n")
        except Exception as e:
            print(f"❌ Key test failed: {e}")
            print("Double-check your key at console.groq.com\n")
    else:
        print("\n⚠️  No API key set. The app will not generate animations.")
        print("Run python setup.py again to add your key.\n")

if __name__ == "__main__":
    main()
